### ISSUE TITLE
[Additional controller] Add validation to the form inputs

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/jaas-dashboard#639] opened 2020-07-31 11:50 UTC
Current there is no validation on the form inputs only help text warning the user. It would be good to validate the input on keydown.

**Comment by hatched** [comment] 2020-07-31 14:05
closing as duplicate of https://github.com/canonical-web-and-design/jaas-dashboard/issues/608

**Closed by hatched** 2020-07-31 14:05 UTC
