### ISSUE TITLE
(Model detail view) Highlight on selection on the row, not cells

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#452] opened 2020-04-23 21:20 UTC
When you select an application in the model detail view, units, machines and relations are highlighted.
It seems we change the background of each cell rather than the entire row, so it has this visual effect:
![Screenshot 2020-04-23 at 22.18.30.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/e4f10dcb-d02e-4328-9d01-f32c6e3b9fce)

Please change the background of the entire row instead of each cell, this should fix this visual bug.

**Comment by hatched** [comment] 2020-04-23 21:22
Closing as duplicate of #450

**Closed by hatched** 2020-04-23 21:22 UTC
