### ISSUE TITLE
Header on the details page isn't full width

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/jaas-dashboard#593] opened 2020-07-13 10:38 UTC
The header should be full width, as on the listing page.

![image](https://user-images.githubusercontent.com/9105999/87295529-46187780-c4fd-11ea-96d9-abeccc705141.png)

**Comment by barrymcgee** [comment] 2020-07-13 13:31
Duplicate of https://github.com/canonical-web-and-design/jaas-dashboard/issues/577

**Closed by barrymcgee** 2020-07-13 13:31 UTC
