### ISSUE TITLE
Relation row highlight doesn't go full width on the table

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#450] opened 2020-04-23 17:11 UTC
When hovering on a row in the relations table the highlight doesn't go to the edge of the table.

![Screen Shot 2020-04-23 at 11.10.04 AM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/cb0f1e40-3b06-4330-ab8e-bd9af50657e6)

**Comment by barrymcgee** [comment] 2020-05-21 09:40
Duplicate of https://github.com/canonical-web-and-design/jaas-dashboard/issues/486

**Closed by barrymcgee** 2020-05-21 09:40 UTC
Labels: Model Details
