### ISSUE TITLE
Config file not loading in production

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#391] opened 2020-03-25 10:29 UTC
https://jaas.ai/models

<img width="1506" alt="Screenshot 2020-03-25 at 10 20 02" src="https://user-images.githubusercontent.com/505570/77527012-5be92a80-6e83-11ea-8a49-ad66a2af5ed9.png">

**Comment by barrymcgee** [comment] 2020-03-25 11:57
https://github.com/canonical-web-and-design/jaas.ai/pull/520

**Comment by hatched** [comment] 2020-03-25 13:37
Closing as duplicate of #389

**Closed by hatched** 2020-03-25 13:37 UTC
