### ISSUE TITLE
If we know the format of inputs, we should validate for them using regex

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#614] opened 2020-07-23 07:59 UTC
<img width="548" alt="Screenshot 2020-07-23 at 08 55 21" src="https://user-images.githubusercontent.com/505570/88263951-ce97d480-ccc2-11ea-9b74-76cdbefd198b.png">

**Comment by hatched** [comment] 2020-07-23 13:31
Closing as duplicate of #608

**Closed by hatched** 2020-07-23 13:31 UTC
Labels: Controllers
