### ISSUE TITLE
Status column for grouped by cloud and owner

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#268] opened 2020-01-06 16:52 UTC
The 'status' column when grouped by cloud and owner should reflect the status 'blocked, alert, running' with the status dots, not 'active'.

![Screenshot 2020-01-06 at 16.42.37.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/59bed966-4035-490c-83b1-e6257cce08da)

![Screenshot 2020-01-06 at 16.42.40.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/6f677a91-a074-4cd0-ae3d-320512291cbf)

**Comment by barrymcgee** [comment] 2020-01-07 14:55
Duplicate of https://github.com/canonical-web-and-design/jaas-dashboard/issues/261

**Closed by barrymcgee** 2020-01-07 14:55 UTC
