### ISSUE TITLE
Cannot open the dashboard after `juju upgrade-model`

### ISSUE THREAD

**Issue by heitorPB** [canonical-web-and-design/jaas-dashboard#1170] opened 2021-11-03 20:31 UTC
**Describe the bug**

I keep seeing the error `Something has gone wrong. If this issue persists, please raise an issue on GitHub.`

**To Reproduce**
1. Go to jimm.xxxxxxxx.com
2. Click on any model
3. See error

**Expected behavior**
No error

**Additional context**
I `juju upgrade-model` and after that I can't open it in the Juju Dashboard.

**Comment by heitorPB** [comment] 2021-11-05 15:12
This error only appears to the models that i have `juju upgrade-model`. The models that I did not run the command work fine.

**Comment by hatched** [comment] 2021-11-05 16:06
Hmm I'm not sure what this could be, what versions did you go between? So that I can try and reproduce the problem.

**Comment by heitorPB** [comment] 2021-11-05 16:54
Upgraded from 2.8.x to 2.9.16:

Our controller was upgraded to 2.9.16
Then dashboard installed and all models worked.
Then I upgraded some models to 2.9.16
Then those models don't open in the dashboard anymore.

**Comment by hatched** [comment] 2021-11-05 17:35
Thanks, I'll try and repro locally shortly and get back to you as off the top of my head there should be no difference between connecting to those different model versions. If you wouldn't mind looking in the browser console (ctrl+shift+i) and pasting here any error messages that you see when this happens.

**Comment by heitorPB** [comment] 2021-11-05 17:50
There's this error here:

```
instrument.ts:129 DOMException: Failed to construct 'WebSocket': The URL 'null' is invalid.
    at Ls.connect (https://jimm.example.com/static/js/main.5d3f7958.chunk.js:1:84689)
    at https://jimm.example.com/static/js/main.5d3f7958.chunk.js:1:85805
    at Ns (https://jimm.example.com/static/js/2.a32b748d.chunk.js:2:685299)
    at t.unstable_runWithPriority (https://jimm.example.com/static/js/2.a32b748d.chunk.js:2:703110)
    at Wi (https://jimm.example.com/static/js/2.a32b748d.chunk.js:2:625470)
    at Cs (https://jimm.example.com/static/js/2.a32b748d.chunk.js:2:684760)
    at https://jimm.example.com/static/js/2.a32b748d.chunk.js:2:684671
    at B (https://jimm.example.com/static/js/2.a32b748d.chunk.js:2:702169)
    at MessagePort._.port1.onmessage (https://jimm.example.com/static/js/2.a32b748d.chunk.js:2:700891)
```

It is a corporate deploy with a Jimm controller, that I replaced the url for `jimm.example.com`.

**Comment by hatched** [comment] 2021-11-05 22:06
This issue appears to be coming from [this line](https://github.com/canonical-web-and-design/jaas-dashboard/blob/main/src/components/WebCLI/WebCLI.js#L36) but I'm not sure why. No question this code should be more resilient to failure however. I'll keep digging next week.

**Comment by hatched** [comment] 2021-11-24 19:30
I have _finally_ been able to reproduce this! I now need to track down the 'why' and fix it.

**Comment by hatched** [comment] 2021-11-24 19:57
The issue is that the `controller-uuid` reported by the model info is now being reported as its actual controller and not JIMM. But because the user doesn't have access to fetch the full controller list it doesn't know where to try and connect for the web CLI websocket connection. I couldn't reproduce this because I always had access to all the controllers. 

This is not a user serviceable fix, a new version of the dashboard will need to be released with a patch to fail gracefully and then a new approach for determining this path will need to be created.

**Closed** 2021-12-03 15:13 UTC
Labels: Priority: High, Bug 🐛

**Comment by heitorPB** [comment] 2021-12-03 16:09
Is this issue fixed in the new version? How do we get the version with the fix?

**Comment by hatched** [comment] 2021-12-03 16:47
Hoping to get a release out today, maybe Monday.

If you wanted to trial it out sooner you can build it from source by cloning the repo and (with node 16 & yarn installed) running `yarn && yarn generate-release-tarball`
