### ISSUE TITLE
Panel content, charm info

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#684] opened 2020-09-16 18:45 UTC
<img width="252" alt="Screenshot 2020-09-16 at 14 06 49" src="https://user-images.githubusercontent.com/1953388/93341335-e3599a00-f825-11ea-986a-9c3ce3675599.png">
I thought we went with this design to allow longer charm name (cs:~hatch/preci...) so the truncation seems unnecesary since there's a lot of space.
That said, we also discussed to implement the other design, since we don't need to display the whole "cs:~hatch/preci..." since it's a link?

**Comment by hatched** [comment] 2020-09-16 19:01
Closing as duplicate of #668

**Closed by hatched** 2020-09-16 19:01 UTC
