### ISSUE TITLE
[bug] When you refresh the page from the browser from a /link the JAAS Dashboard returns a 404

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#273] opened 2020-01-08 17:34 UTC
Open the Dashboard, it redirects to https://dashboard.staging.jaas.ai/models
But if refresh the page with that link or go to that link from a new window (or any other link such as /controllers) it returns a 404.

**Comment by hatched** [comment] 2020-01-08 18:13
Closing as duplicate of #259

**Closed by hatched** 2020-01-08 18:13 UTC
