### ISSUE TITLE
Add notification when unable to view model details because of request timeouts/errors

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#299] opened 2020-01-21 13:57 UTC
It seems there's a block that prevents us to open two windows of the dashboard in two browser window (e.g. to have two or more models on different windows). Can we investigate?

**Comment by hatched** [comment] 2020-01-21 14:03
I'm not able to reproduce, can you expand with some step-by-step instructions on how to reproduce and what errors you're seeing. Please make sure you don't have any extensions blocking api requests like ublock or privacy badger

**Comment by hatched** [comment] 2020-01-27 19:47
I was able to reproduce this today. It appears that if you have too many active requests open then the models refuse the connections. This is outside of our control and doesn't appear to have a consistent threshold as I've had many tabs open from different browsers and it worked fine and other times only a single additional tab causes them to fail. 

The only solution I can think of is if we know that a status request has failed we could indicate as such in the UI with some tips on how to get it back.

This however may only be temporarily required, as the new watcher API will dramatically reduce the  request load.

**Comment by hatched** [comment] 2020-01-28 22:12
@clagom @spencerbygraves Could we get some design work on what the model details page might look like in the event that we're unable to fetch the model status because of a timeout or error?

**Comment by clagom** [comment] 2020-01-29 09:06
Sure @hatched, adding this issue to planning

**Comment by hatched** [comment] 2020-10-08 14:56
Closing this issue as it'll be resolved with the switch to the new watcher endpoints.

**Closed by hatched** 2020-10-08 14:56 UTC
Labels: Model Details, Priority: Low
