### ISSUE TITLE
Regression on topology modal window - no topology

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#403] opened 2020-03-31 20:48 UTC
The modal window with the enlarged topology stopped working, doesn't display the topology of the model:
![Screenshot 2020-03-31 at 21.46.54.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/a0ea2259-4c4f-4ca4-a721-c69710469ff7)

Open a model, click on the topology [+]

**Comment by hatched** [comment] 2020-03-31 21:07
I'm not able to reproduce this but I do recall seeing it on your machine. Are you able to reproduce this? Can you provide some reproduction steps? Or even any error messages that are in the browser console.

**Comment by clagom** [comment] 2020-03-31 21:13
@hatched 
It seems a CSS issue?
Opened another model and this is what I saw once clicked on the topology:
<img width="200" alt="Screenshot 2020-03-31 at 22 11 13" src="https://user-images.githubusercontent.com/1953388/78075603-c0811980-739c-11ea-82ab-46e4b275a7df.png">

Playing around with fixed width and height and overflow visible I could change to this:
<img width="1680" alt="Screenshot 2020-03-31 at 22 12 16" src="https://user-images.githubusercontent.com/1953388/78075627-cbd44500-739c-11ea-9f93-442d0d2e4275.png">

The console:
<img width="1680" alt="Screenshot 2020-03-31 at 22 13 34" src="https://user-images.githubusercontent.com/1953388/78075680-e3133280-739c-11ea-9c29-f290db21ca34.png">

**Comment by hatched** [comment] 2020-03-31 21:18
Thanks @clagom Also confirming with @barrymcgee it looks like it's an issue in Chrome but not in Firefox and related to the `viewbox` PR that landed recently.

**Closed** 2020-04-02 15:03 UTC
Labels: Priority: High, Topology
