### ISSUE TITLE
Log Out does not work

### ISSUE THREAD

**Issue by moula** [canonical-web-and-design/jaas-dashboard#522] opened 2020-05-28 06:18 UTC
It is not possible to disconnect. Pressing the "Log out" button and still not on.
![Screenshot_2020-05-28 JAAS Dashboard(3)](https://user-images.githubusercontent.com/1804815/83105916-d6207000-a0bb-11ea-943c-b9562d149d93.png)

**Comment by barrymcgee** [comment] 2020-05-28 07:24
Duplicate of https://github.com/canonical-web-and-design/jaas-dashboard/issues/465

**Comment by hatched** [comment] 2020-05-28 13:44
Hi @moula thanks for filing this issue. 

You'll note that this has been marked as a duplicate. You have been logged out, private information cleared, etc. The UI just has a bug to which it's not presenting you with the log in screen again.

**Closed by hatched** 2020-05-28 13:44 UTC
