### ISSUE TITLE
[UX] Better user experience when no models on jaas.ai

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#1057] opened 2021-06-17 15:55 UTC
This is an issue when users without models log-in (first time or not) to the JAAS dashboard (on jaas.ai/models) without having deployed models.
All we display at the moment is the spinner. Users can access to controller page, but models page displays just the spinner. Initially, the username is not visible on the bottom-left, it appears when clicking on "controllers" or on "models" again.

Maybe we can take guidelines from the recent work of @amylily1011 and @wgx on empty states. Not a complete "onboarding" experience yet, but would help users without models.

**Comment by hatched** [comment] 2021-06-17 15:56
Closing as duplicate of #1012

**Closed by hatched** 2021-06-17 15:56 UTC
