### ISSUE TITLE
unexpected error message after external login

### ISSUE THREAD

**Issue by kampar2021** [canonical-web-and-design/jaas-dashboard#1013] opened 2021-05-27 21:03 UTC
**Describe the bug**
Trying to open the juju dashboard from browser and login thru external identity provider gives unexpected error message on models page, but opening controllers page opens fine.

**To Reproduce**
Juju dashboard verions 0.6.2 beta
1. Go to 'https://juju-server:17070/dashboard'
2. Click on 'Login to JaaS' button
3. Gets redirected to Candid URL for login, provide user credential
4. Candid confirms user logged in successfully
5. juju dashboard redirects to https://juju-server:17070/dashboard/models
6. Jaas Dashboard gives error "Error: Something has gone wrong. If this issue persists, please raise an issue on GitHub."
7. if we ignore the error and change the URL to https://172.25.164.201:17070/dashboard/controllers
8. Controllers page loads up properly and show controller, machine, instance information and show that user has access to 3 models
9. Here also if clicked on Models link, same error mentioned above repeats.

**Expected behavior**
I would expect the dashboard to show all models to which user has access.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows server
 - Browser Chrome 90.0.4430.212, Firefox 88.0.1

**Smartphone (please complete the following information):**

**Additional context**
Looking at browser console it shows errors for 
TypeError: e is undefined
    highlightSubString utils.js:19
    h FilterPanelSection.js:123
    h FilterPanelSection.js:120
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    Redux 5
    Hs check-auth.js:75
    Me actions.js:71

**Comment by hatched** [comment] 2021-05-27 21:06
Thanks for filing this issue @kampar2021 I actually JUST merged a fix for this. I'll try and get a release out tomorrow with that fix. 

I'll update here when that's gone out.

**Comment by hatched** [comment] 2021-06-02 03:38
This should be resolved in the dashboard version 0.7.1. You can upgrade any existing controllers with `juju upgrade-dashboard`. Feel free to re-open this issue if this doesn't resolve it and we'll have to take another look.

**Comment by kampar2021** [comment] 2021-06-04 21:27
I upgrade the ersion 0.7.1 and I am still getting the errors on models page

below is captured in browser console  log

TypeError: e is undefined
    highlightSubString utils.js:19
    h FilterPanelSection.js:123
    h FilterPanelSection.js:120
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    r helpers.ts:87
    _wrapEventTarget trycatch.ts:185
    M instrument.ts:559
    React 8
    ia index.js:99
    ia index.js:51
    528 index.js:54
    a controllers:1
    t controllers:1
    r controllers:1
    <anonymous> main.78fcf2fe.chunk.js:1
instrument.ts:129:35
    M instrument.ts:129
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    r helpers.ts:87
    (Async: EventListener.handleEvent)
    _wrapEventTarget trycatch.ts:185
    M instrument.ts:559
    React 8
    ia index.js:99
    ia index.js:51
    528 index.js:54
    a controllers:1
    t controllers:1
    r controllers:1
    <anonymous> main.78fcf2fe.chunk.js:1

**Comment by hatched** [comment] 2021-06-04 22:59
So it turns out I merged a fix for an unrelated issue around external identity providers. :)

I think that the external auth is a red herring as it appears that the issue is coming from the `SearchAndFilter` component from our component library and not something to do with the login system.

While I'm not able to reproduce this might be happening because the `heading` being passed into `highlightSubString` [here](https://github.com/canonical-web-and-design/react-components/blob/master/src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.js#L99) is `undefined` and when it tries to call `str.replace` it fails. This function should be more robust to invalid values. If the data is bad I'm not sure how it gets all the way to this point before failing however...

Would you be interested in running a different version of the dashboard that will output more detailed information into the console so that I can gather a bit more information on this failure?

**Comment by kampar2021** [comment] 2021-06-15 14:22
> So it turns out I merged a fix for an unrelated issue around external identity providers. :)
> 
> I think that the external auth is a red herring as it appears that the issue is coming from the `SearchAndFilter` component from our component library and not something to do with the login system.
> 
> While I'm not able to reproduce this might be happening because the `heading` being passed into `highlightSubString` [here](https://github.com/canonical-web-and-design/react-components/blob/master/src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.js#L99) is `undefined` and when it tries to call `str.replace` it fails. This function should be more robust to invalid values. If the data is bad I'm not sure how it gets all the way to this point before failing however...
> 
> Would you be interested in running a different version of the dashboard that will output more detailed information into the console so that I can gather a bit more information on this failure?

sure let me know the details and I will deploy that.

**Closed** 2021-07-28 16:39 UTC
Labels: Priority: Critical
