### ISSUE TITLE
User/Pass login box should have 'Remember me' functionality

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#913] opened 2021-03-10 09:31 UTC
**Is your feature request related to a problem? Please describe.**

When working on a bootstrapped controller, I'm often asked to reauth within a short period. 

**Describe the solution you'd like**

We should have a 'Remember this browser' tickbox which would persist the login session for a set period of time - 30 days?

<img width="415" alt="Screenshot 2021-03-10 at 09 29 01" src="https://user-images.githubusercontent.com/505570/110607725-64656e80-8183-11eb-958a-29eae6080aa5.png">

**Comment by hatched** [comment] 2021-03-10 15:50
Closing as duplicate of #477

**Closed by hatched** 2021-03-10 15:50 UTC
