### ISSUE TITLE
Registering a controller that doesn't exist will crash the app

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#620] opened 2020-07-23 12:24 UTC
To test the form validation, I registered a controller locally with random strings - now I can't start the app. 

<img width="1064" alt="Screenshot 2020-07-23 at 13 21 15" src="https://user-images.githubusercontent.com/505570/88285843-b38b8b80-cce7-11ea-9a5d-b0b98616e427.png">

**Comment by hatched** [comment] 2020-07-23 13:37
Closing as duplicate of #611

**Closed by hatched** 2020-07-23 13:37 UTC
