### ISSUE TITLE
Table layout auto spreads the space between tables

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/jaas-dashboard#135] opened 2019-10-30 23:05 UTC
With the `.u-table-layout--auto` applied to tables in FF is spreading the padding around tables:
![Screenshot_2019-10-30 JAAS Dashboard](https://user-images.githubusercontent.com/1413534/67905601-d24e5e80-fb69-11e9-8099-987ef0814e14.png)

**Comment by hatched** [comment] 2019-10-31 01:58
Closing as duplicate of https://github.com/canonical-web-and-design/jaas-dashboard/issues/109

**Closed by hatched** 2019-10-31 01:58 UTC
